apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-cluster-1
  region: eu-west-1

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.medium
    desiredCapacity: 2

cloudWatch:
    clusterLogging:
        enableTypes: ["audit", "authenticator", "controllerManager"]
