apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-autoscaling
  annotations:
    ad.datadoghq.com/nodebb-app.logs: '[{"source":"nodebb-app","service":"nodebb-app"}]'
  labels:
    app : my-k8s-deployment
spec:
  selector:
    matchLabels:
      project: nodebb
  template:
    metadata:
      labels:
        project: nodebb
    spec:
      containers:
        - name : nodebb-app
          image: 140625812000.dkr.ecr.eu-west-1.amazonaws.com/nodebb-test:latest
          ports:
            - containerPort: 4567
