apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
     env  : prod
spec:
  selector:
    project: nodebb
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80
      targetPort: 4567
  type: LoadBalancer
