name: Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Kubectl get nodes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get nodes
